# Array: 
- central data structure of the NumPy library
- contains information about raw data
- a grid of elements can be indexed in many ways
- elements are all of the same type, referred to as the array dtype
- an array can be indexed by a tuple of non-negative integers, by Booleans, by another array or by integers.

In [9]:
import numpy as np
a= np.array([5,5,5,])
type(a)

numpy.ndarray

In [11]:
a

array([5, 5, 5])

In [48]:
a= np.array([[5,5,5], [5, 5, 5], [5, 5, 5]])
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [50]:
type(a)

numpy.ndarray

## vector
- one dimensional array is vector
- no difference between rows and columns
## matrix
- two dimensional array is a *matrix*

In [25]:
import numpy as np
a= np.array([5,5,5,])
a

array([5, 5, 5])

In [27]:
type(a)

numpy.ndarray

In [29]:
len(a)

3

In [42]:
b= np.array([[5,5,5], [5, 5, 5], [5, 5, 5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [38]:
type(b)

numpy.ndarray

In [40]:
len(b)

3

## 3-D array
- the term *tensor* is commonly used for 3-D or higher dimensional arrays
### array attributes
- dimension are called axis
      -there are two axis in a matrix (2-D)
- first axis is column(vertical)
- second axis is row(horizontal)

# 1-D array creation

In [56]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [58]:
b= np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [60]:
c= np.ones(3)
c

array([1., 1., 1.])

In [62]:
# create an empty array with 3 elements
d= np.empty(3)
d

array([1., 1., 1.])

In [64]:
# with range of elements
e= np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [68]:
# with specific range of elements
f= np.arange(2, 9)
f

array([2, 3, 4, 5, 6, 7, 8])

In [70]:
# continue...
g= np.arange(2, 20, 2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
# linearly spaces arrays
h=np.linspace(0,10,num=5) #gives five numbers
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [78]:
# specific data types in array
i= np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [82]:
j= np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

## 2-D array creation

In [92]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [108]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3-D array creation

In [112]:
# making and reshaping a 3D array
c= np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])