# numpy practice

In [2]:
# pip install library (if not installed)

In [6]:
# import numpy library in jupyter notebook
import numpy as np

# Creating an array using numpy

In [5]:
food= np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [6]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [7]:
type(price)

numpy.ndarray

In [8]:
type(food)

numpy.ndarray

In [9]:
len(food)

3

In [10]:
len(price)

3

In [11]:
food[2]

'Raita'

In [12]:
food[0]

'Pakora'

In [13]:
food[0:]

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [14]:
price.mean()

5.0

In [15]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [49]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(2, 40)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39])

In [51]:
# range specfic interval
np.arange(2, 30, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [53]:
np.arange(5,55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [59]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
# line space
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [8]:
# specify data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [10]:
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [14]:
np.ones(10, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [20]:
a = np.array([10,12, 15, 2, 4, 6, 100, 230, 0.5, 10.2])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 230. ,   0.5,
        10.2])

In [24]:
# sorting of array
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.2,  12. ,  15. , 100. ,
       230. ])

In [30]:
b= np.array([10.2, 3.4, 53.6, 62.9, 12.4])
b

array([10.2,  3.4, 53.6, 62.9, 12.4])

In [32]:
c= np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.2,  12. ,  15. , 100. ,
       230. ,  10.2,   3.4,  53.6,  62.9,  12.4])

In [34]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.2,  12. ,
        12.4,  15. ,  53.6,  62.9, 100. , 230. ])

# 2-D array

In [39]:
a= np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [43]:
b= np.array([[6, 7, 8, 9, 10], [10, 9, 8, 7, 6]])
b

array([[ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [55]:
c= np.concatenate((a, b), axis=0) 
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [59]:
c.sort()
c

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [8]:
a= np.array([[[0,1,2,3], [4,5,6,7]], [[0,1,2,3], [4,5,6,7]], [[0,1,2,3], [4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [10]:
# to find the number of dimensions
a.ndim

3

In [14]:
b= np.array([[5,6,7],
            [8,9,10],
            [11,12,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [16]:
b.ndim

2

In [22]:
# size of elements
a.size

24

In [20]:
b.size

9

In [24]:
a.shape

(3, 2, 4)

In [30]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [36]:
# reshape
b= a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
np.reshape(a, newshape=(2,3), order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [58]:
# convert 1-D to 2-D
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
a.shape

(9,)

In [64]:
# row wise 2D conversion
b= a[np.newaxis, :]
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [66]:
b.shape

(1, 9)

In [70]:
# column wise 2D conversion
c= a[:, np.newaxis]
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [74]:
a[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [78]:
a+6

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
a*6

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48])

In [82]:
a.sum()

36

In [84]:
a.mean()

4.0